"""Oracle-based generated validation for problem packages.

The execution path delegates to ``harness.run_case()`` so generated validation
does not become a second judge.
"""

from __future__ import annotations

from dataclasses import dataclass
import os
import random
from typing import Any, Callable

from pv.errors import ImportPolicyError, PVError
from pv.harness import load_cases, load_problem_meta, run_case
from pv.submission_policy import check_imports


class ProblemValidationError(PVError):
    """Raised when generated validation is not available for a problem."""

    def __init__(self, message: str):
        super().__init__(message, user_message=message)


def two_sum_oracle(nums: list[int], target: int) -> list[int]:
    """Return the first Two Sum index pair by independent O(n^2) search."""
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            if nums[i] + nums[j] == target:
                return [i, j]
    raise ProblemValidationError(
        f"Two Sum oracle found no answer for nums={nums!r}, target={target!r}"
    )


def _valid_two_sum_pairs(nums: list[int], target: int) -> list[list[int]]:
    pairs: list[list[int]] = []
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            if nums[i] + nums[j] == target:
                pairs.append([i, j])
    return pairs


def _generated_case(
    problem_id: str,
    seed: int,
    index: int,
    args: dict[str, Any],
    expected: Any,
) -> dict[str, Any]:
    return {
        "name": f"{problem_id} generated seed={seed} case={index}",
        "args": args,
        "expected": expected,
        "notes": "Generated by oracle-based validation.",
    }


def _validate_count(count: int) -> None:
    if count < 0:
        raise ProblemValidationError("--generated must be >= 0")


def generate_two_sum_cases(count: int, seed: int = 0) -> list[dict[str, Any]]:
    """Generate deterministic Two Sum cases with exactly one valid answer."""
    _validate_count(count)

    rng = random.Random(seed)
    cases: list[dict[str, Any]] = []
    attempts = 0
    max_attempts = max(1000, count * 200)

    while len(cases) < count and attempts < max_attempts:
        attempts += 1
        n = rng.randint(2, 12)
        nums = [rng.randint(-30, 30) for _ in range(n)]
        i, j = sorted(rng.sample(range(n), 2))
        target = nums[i] + nums[j]

        pairs = _valid_two_sum_pairs(nums, target)
        if len(pairs) != 1:
            continue

        expected = two_sum_oracle(nums, target)
        cases.append(
            _generated_case(
                "0001_two_sum",
                seed,
                len(cases),
                {"nums": nums, "target": target},
                expected,
            )
        )

    if len(cases) < count:
        raise ProblemValidationError(
            f"Could only generate {len(cases)} unique-answer cases after {attempts} attempts."
        )
    return cases


def container_with_most_water_oracle(height: list[int]) -> int:
    """Return max container area by independent O(n^2) pair enumeration."""
    best = 0
    for i in range(len(height)):
        for j in range(i + 1, len(height)):
            area = (j - i) * min(height[i], height[j])
            if area > best:
                best = area
    return best


def generate_container_with_most_water_cases(
    count: int,
    seed: int = 0,
) -> list[dict[str, Any]]:
    """Generate deterministic Container With Most Water cases."""
    _validate_count(count)
    rng = random.Random(seed)
    heights = [
        [0, 0, 0, 0],
        [5, 5, 5, 5],
        [1, 2, 3, 4, 5, 6],
        [6, 5, 4, 3, 2, 1],
        [9, 1, 1, 1, 9],
        [1, 8, 10, 8, 1],
    ]

    cases: list[dict[str, Any]] = []
    while len(cases) < count:
        if len(cases) < len(heights):
            height = list(heights[len(cases)])
        else:
            height = [rng.randint(0, 20) for _ in range(rng.randint(2, 12))]
        cases.append(
            _generated_case(
                "0011_container_with_most_water",
                seed,
                len(cases),
                {"height": height},
                container_with_most_water_oracle(height),
            )
        )
    return cases


def climbing_stairs_oracle(n: int) -> int:
    """Return number of ways using an independent DP recurrence."""
    if n < 1:
        raise ProblemValidationError(
            f"Climbing Stairs oracle requires n >= 1, got {n!r}"
        )
    prev2 = 1
    prev1 = 1
    for _ in range(2, n + 1):
        prev2, prev1 = prev1, prev1 + prev2
    return prev1


def generate_climbing_stairs_cases(count: int, seed: int = 0) -> list[dict[str, Any]]:
    """Generate deterministic Climbing Stairs cases."""
    _validate_count(count)
    rng = random.Random(seed)
    values = [1, 2, 3, 10, 20]

    cases: list[dict[str, Any]] = []
    while len(cases) < count:
        if len(cases) < len(values):
            n = values[len(cases)]
        else:
            n = rng.randint(1, 30)
        cases.append(
            _generated_case(
                "0070_climbing_stairs",
                seed,
                len(cases),
                {"n": n},
                climbing_stairs_oracle(n),
            )
        )
    return cases


def house_robber_oracle(nums: list[int]) -> int:
    """Return max non-adjacent sum by independent brute-force enumeration."""
    best = 0
    for mask in range(1 << len(nums)):
        total = 0
        previous_chosen = False
        valid = True
        for i, amount in enumerate(nums):
            chosen = bool(mask & (1 << i))
            if chosen and previous_chosen:
                valid = False
                break
            if chosen:
                total += amount
            previous_chosen = chosen
        if valid and total > best:
            best = total
    return best


def generate_house_robber_cases(count: int, seed: int = 0) -> list[dict[str, Any]]:
    """Generate deterministic House Robber cases."""
    _validate_count(count)
    rng = random.Random(seed)
    values = [
        [],
        [7],
        [0, 0, 0, 0],
        [10, 1, 10, 1, 10],
        [1, 100, 100, 1],
    ]

    cases: list[dict[str, Any]] = []
    while len(cases) < count:
        if len(cases) < len(values):
            nums = list(values[len(cases)])
        else:
            nums = [rng.randint(0, 30) for _ in range(rng.randint(0, 12))]
        cases.append(
            _generated_case(
                "0198_house_robber",
                seed,
                len(cases),
                {"nums": nums},
                house_robber_oracle(nums),
            )
        )
    return cases


def reverse_linked_list_oracle(head: list[int]) -> list[int]:
    """Return reversed linked-list values using Python list reversal."""
    return list(reversed(head))


def generate_reverse_linked_list_cases(
    count: int,
    seed: int = 0,
) -> list[dict[str, Any]]:
    """Generate deterministic Reverse Linked List cases."""
    _validate_count(count)
    rng = random.Random(seed)
    values = [
        [],
        [5],
        [2, 2, 2],
        [1, 2, 3, 4, 5],
    ]

    cases: list[dict[str, Any]] = []
    while len(cases) < count:
        if len(cases) < len(values):
            head = list(values[len(cases)])
        else:
            head = [rng.randint(-9, 9) for _ in range(rng.randint(0, 10))]
        cases.append(
            _generated_case(
                "0206_reverse_linked_list",
                seed,
                len(cases),
                {"head": head},
                reverse_linked_list_oracle(head),
            )
        )
    return cases


@dataclass(frozen=True)
class ValidationSpec:
    generate_cases: Callable[[int, int], list[dict[str, Any]]]


VALIDATION_SPECS: dict[str, ValidationSpec] = {
    "0001_two_sum": ValidationSpec(generate_two_sum_cases),
    "0011_container_with_most_water": ValidationSpec(
        generate_container_with_most_water_cases
    ),
    "0070_climbing_stairs": ValidationSpec(generate_climbing_stairs_cases),
    "0198_house_robber": ValidationSpec(generate_house_robber_cases),
    "0206_reverse_linked_list": ValidationSpec(generate_reverse_linked_list_cases),
}


def _empty_counts(total: int = 0) -> dict[str, int]:
    return {"passed": 0, "total": total}


def _failure(source: str, index: int, case: dict, result: dict) -> dict[str, Any]:
    return {"source": source, "index": index, "case": case, "result": result}


def validate_problem(
    problem_dir: str,
    generated_count: int,
    seed: int,
    solution_file: str = "solution.py",
) -> dict[str, Any]:
    """Validate fixed and generated cases for one supported problem."""
    meta = load_problem_meta(problem_dir)
    problem_id = meta.get("problem_id")
    spec = VALIDATION_SPECS.get(problem_id)
    if spec is None:
        supported = ", ".join(sorted(VALIDATION_SPECS))
        raise ProblemValidationError(
            f"validate-problem has no validation spec for {problem_id!r}. "
            f"Supported problems: {supported}."
        )

    solution_path = os.path.join(problem_dir, solution_file)
    policy_result = check_imports(solution_path)
    if not policy_result["ok"]:
        msg = "代码包含不允许的导入：\n" + "\n".join(
            f"  • {v}" for v in policy_result["violations"]
        )
        raise ImportPolicyError(detail=msg, user_message=msg)

    fixed_cases = load_cases(problem_dir)
    generated_cases = spec.generate_cases(generated_count, seed)
    summary: dict[str, Any] = {
        "problem_id": problem_id,
        "passed": True,
        "fixed": _empty_counts(len(fixed_cases)),
        "generated": _empty_counts(len(generated_cases)),
        "first_failure": None,
    }

    for i, case in enumerate(fixed_cases):
        result = run_case(meta, case, solution_path, save_trace=False, case_index=i)
        if not result["passed"]:
            summary["passed"] = False
            summary["first_failure"] = _failure("fixed", i, case, result)
            return summary
        summary["fixed"]["passed"] += 1

    for i, case in enumerate(generated_cases):
        result = run_case(
            meta,
            case,
            solution_path,
            save_trace=False,
            case_index=len(fixed_cases) + i,
        )
        if not result["passed"]:
            summary["passed"] = False
            summary["first_failure"] = _failure("generated", i, case, result)
            return summary
        summary["generated"]["passed"] += 1

    return summary
