"""Oracle-based generated validation for problem packages.

Phase 6.2 intentionally supports only 0001 Two Sum.  The execution path
delegates to ``harness.run_case()`` so generated validation does not become
a second judge.
"""

from __future__ import annotations

import os
import random
from typing import Any

from pv.errors import ImportPolicyError, PVError
from pv.harness import load_cases, load_problem_meta, run_case
from pv.submission_policy import check_imports


class ProblemValidationError(PVError):
    """Raised when generated validation is not available for a problem."""

    def __init__(self, message: str):
        super().__init__(message, user_message=message)


def two_sum_oracle(nums: list[int], target: int) -> list[int]:
    """Return the first Two Sum index pair by independent O(n^2) search."""
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            if nums[i] + nums[j] == target:
                return [i, j]
    raise ProblemValidationError(
        f"Two Sum oracle found no answer for nums={nums!r}, target={target!r}"
    )


def _valid_two_sum_pairs(nums: list[int], target: int) -> list[list[int]]:
    pairs: list[list[int]] = []
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            if nums[i] + nums[j] == target:
                pairs.append([i, j])
    return pairs


def generate_two_sum_cases(count: int, seed: int = 0) -> list[dict[str, Any]]:
    """Generate deterministic Two Sum cases with exactly one valid answer."""
    if count < 0:
        raise ProblemValidationError("--generated must be >= 0")

    rng = random.Random(seed)
    cases: list[dict[str, Any]] = []
    attempts = 0
    max_attempts = max(1000, count * 200)

    while len(cases) < count and attempts < max_attempts:
        attempts += 1
        n = rng.randint(2, 12)
        nums = [rng.randint(-30, 30) for _ in range(n)]
        i, j = sorted(rng.sample(range(n), 2))
        target = nums[i] + nums[j]

        pairs = _valid_two_sum_pairs(nums, target)
        if len(pairs) != 1:
            continue

        expected = two_sum_oracle(nums, target)
        cases.append(
            {
                "name": f"generated seed={seed} case={len(cases)}",
                "args": {"nums": nums, "target": target},
                "expected": expected,
                "notes": "Generated by oracle-based validation.",
            }
        )

    if len(cases) < count:
        raise ProblemValidationError(
            f"Could only generate {len(cases)} unique-answer cases after {attempts} attempts."
        )
    return cases


def _empty_counts(total: int = 0) -> dict[str, int]:
    return {"passed": 0, "total": total}


def _failure(source: str, index: int, case: dict, result: dict) -> dict[str, Any]:
    return {"source": source, "index": index, "case": case, "result": result}


def validate_problem(
    problem_dir: str,
    generated_count: int,
    seed: int,
    solution_file: str = "solution.py",
) -> dict[str, Any]:
    """Validate fixed and generated cases for one supported problem."""
    meta = load_problem_meta(problem_dir)
    problem_id = meta.get("problem_id")
    if problem_id != "0001_two_sum":
        raise ProblemValidationError(
            f"validate-problem currently supports only 0001_two_sum, got {problem_id!r}."
        )

    solution_path = os.path.join(problem_dir, solution_file)
    policy_result = check_imports(solution_path)
    if not policy_result["ok"]:
        msg = "代码包含不允许的导入：\n" + "\n".join(
            f"  • {v}" for v in policy_result["violations"]
        )
        raise ImportPolicyError(detail=msg, user_message=msg)

    fixed_cases = load_cases(problem_dir)
    generated_cases = generate_two_sum_cases(generated_count, seed)
    summary: dict[str, Any] = {
        "problem_id": problem_id,
        "passed": True,
        "fixed": _empty_counts(len(fixed_cases)),
        "generated": _empty_counts(len(generated_cases)),
        "first_failure": None,
    }

    for i, case in enumerate(fixed_cases):
        result = run_case(meta, case, solution_path, save_trace=False, case_index=i)
        if not result["passed"]:
            summary["passed"] = False
            summary["first_failure"] = _failure("fixed", i, case, result)
            return summary
        summary["fixed"]["passed"] += 1

    for i, case in enumerate(generated_cases):
        result = run_case(
            meta,
            case,
            solution_path,
            save_trace=False,
            case_index=len(fixed_cases) + i,
        )
        if not result["passed"]:
            summary["passed"] = False
            summary["first_failure"] = _failure("generated", i, case, result)
            return summary
        summary["generated"]["passed"] += 1

    return summary
